version: '3.8'

services:
  db:
    image: postgres:15.8
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: mydb
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - internal
    restart: always

  backend:
    build: ./desafio-tecnico/backend
    env_file:
      - ./desafio-tecnico/backend/.env 
    ports:
      - 3001:3001
    networks:
      - internal
    restart: always
  frontend:
    build: ./desafio-tecnico/frontend
    ports:
      - 8081:80
    networks:
      - external
    restart: always

networks:
  internal:
  external:
